load("//tools/rules/golang:defs.bzl", "opensqs_go_test")

opensqs_go_test(
    name = "go_default_test",
    srcs = ["metrics_test.go"],
    deps = [
        "//apps/go/server/metrics:go_default_library",
        "@com_github_prometheus_client_golang//prometheus:go_default_library",
        "@com_github_prometheus_client_golang//prometheus/promhttp:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
    ],
)
