{{- include "opensqs.validateSecret" . -}}
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensqs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensqs.labels" . | nindent 4 }}
type: Opaque
stringData:
  serverSecret: {{ .Values.opensqs.sqs.serverSecret | quote }}
{{- end }}
