apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensqs.fullname" . }}
  labels:
    {{- include "opensqs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: sqs
      port: {{ .Values.service.port }}
      targetPort: sqs
      protocol: TCP
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: ui
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "opensqs.selectorLabels" . | nindent 4 }}
