load("//tools/rules/golang:defs.bzl", "opensqs_go_binary", "opensqs_go_library")

opensqs_go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "github.com/tguidoux/opensqs/apps/go/playground/cmd_hello_world",
    visibility = ["//visibility:private"],
)

opensqs_go_binary(
    name = "cmd_hello_world",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
