load("//tools/rules/golang:defs.bzl", "opensqs_go_library")

opensqs_go_library(
    name = "go_default_library",
    srcs = [
        "errors.go",
        "json.go",
        "marshal.go",
        "query.go",
    ],
    importpath = "github.com/tguidoux/opensqs/apps/go/server/protocol",
    visibility = ["//visibility:public"],
    deps = ["//pkgs/v1/queue/types:go_default_library"],
)
