load("//tools/rules/golang:defs.bzl", "opensqs_go_library")

opensqs_go_library(
    name = "go_default_library",
    srcs = [
        "actions_batch.go",
        "actions_dlq.go",
        "actions_message.go",
        "actions_permissions.go",
        "actions_queue.go",
        "actions_tags.go",
        "adapter_json.go",
        "adapter_query.go",
        "handler.go",
        "helpers.go",
        "marshal.go",
        "message_builder.go",
    ],
    importpath = "github.com/tguidoux/opensqs/apps/go/server/handlers",
    visibility = ["//visibility:public"],
    deps = [
        "//apps/go/server/metrics:go_default_library",
        "//apps/go/server/protocol:go_default_library",
        "//pkgs/v1/id:go_default_library",
        "//pkgs/v1/logger:go_default_library",
        "//pkgs/v1/queue:go_default_library",
        "//pkgs/v1/queue/dlq:go_default_library",
        "//pkgs/v1/queue/types:go_default_library",
    ],
)
